"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { SidecarStatus } from "@vault/types";
import { usePreferences, type Preferences } from "@/hooks/usePreferences";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { toast } from "@/components/ui/Toaster";
import { Download, Loader2, Save } from "lucide-react";
import {
  exportSidecarSnapshot,
  getSidecarStatus,
  startSidecarRestore,
} from "@/lib/media/sidecars";
import { formatBytes } from "@/lib/media/utils";

const POLL_MS = 2000;

function formatWhen (iso: string): string {
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? "recently" : date.toLocaleString();
}

/** Snapshot on/off, last-snapshot summary, and the export/restore actions. */
export function MetadataBackupCard () {
  const { prefs, updatePreferences, isLoaded } = usePreferences();
  const [status, setStatus] = useState<SidecarStatus | null>(null);
  const [exporting, setExporting] = useState(false);
  const [confirming, setConfirming] = useState(false);

  // So the completion toast fires once, and only for a run this tab started.
  const pendingRef = useRef(false);

  const refresh = useCallback(async () => {
    const next = await getSidecarStatus();
    setStatus(next);
    if (pendingRef.current && next?.restore && next.restore.state !== "running") {
      pendingRef.current = false;
      if (next.restore.state === "failed") {
        toast(`Restore failed — ${next.restore.message}`, { variant: "error" });
      } else if (next.restore.state === "interrupted") {
        toast("Restore stopped before it finished — you can run it again.", { variant: "error" });
      } else {
        const r = next.restore.result;
        toast(
          `Restore complete — ${r.updated} item${r.updated === 1 ? "" : "s"} updated, ${r.tagsRestored} tag${r.tagsRestored === 1 ? "" : "s"} put back.`,
          { variant: "success" },
        );
      }
    }
  }, []);

  useEffect(() => { void refresh(); }, [refresh]);

  const restoring = status?.restore?.state === "running";
  useEffect(() => {
    if (!restoring) return;
    const id = setInterval(() => void refresh(), POLL_MS);
    return () => clearInterval(id);
  }, [restoring, refresh]);

  const handleExport = useCallback(async () => {
    setExporting(true);
    try {
      const result = await exportSidecarSnapshot();
      toast(`Snapshot written — ${result.entries} item${result.entries === 1 ? "" : "s"}.`, { variant: "success" });
      await refresh();
    } catch (err) {
      toast(err instanceof Error ? err.message : "Could not write the snapshot", { variant: "error" });
    } finally {
      setExporting(false);
    }
  }, [refresh]);

  const handleRestore = useCallback(async () => {
    setConfirming(false);
    try {
      await startSidecarRestore();
      pendingRef.current = true;
      await refresh();
    } catch (err) {
      toast(err instanceof Error ? err.message : "Could not start the restore", { variant: "error" });
    }
  }, [refresh]);

  // The server flag wins over the preference: SIDECAR_EXPORT_ENABLED=false
  // means no snapshot will ever be written whatever this account has chosen.
  const serverDisabled = status?.enabled === false;
  const enabled = prefs.sidecarMode === "snapshot" && !serverDisabled;

  return (
    <Card>
      <CardHeader className="pb-4">
        <CardTitle>Metadata backup</CardTitle>
        <CardDescription className="mt-1">
          Your tags, renamed titles, starred items, bundles and reminders live only in
          Vault&apos;s database — the files themselves carry none of it. Vault periodically
          writes them all to a single snapshot file in its own storage, so losing the
          database means rescanning your folders and pressing Restore, not starting over.
          Nothing is ever written into your own folders.
        </CardDescription>
      </CardHeader>

      <CardContent className="px-6 pb-6 pt-0 space-y-4">
        <div className="flex items-start justify-between gap-6 py-3 border-b border-border">
          <div className="space-y-0.5">
            <label htmlFor="sidecar-mode" className="text-sm font-medium">
              Automatic snapshots
            </label>
            <p className="text-xs text-muted-foreground">
              Rewritten every few minutes, but only when something changed.
              Extracted text is left out — it is regenerated by re-running OCR.
            </p>
          </div>
          <div className={`shrink-0 transition-opacity ${!isLoaded || serverDisabled ? "opacity-50 pointer-events-none" : ""}`}>
            <select
              id="sidecar-mode"
              value={serverDisabled ? "off" : prefs.sidecarMode}
              disabled={!isLoaded || serverDisabled}
              onChange={e => updatePreferences({ sidecarMode: e.target.value as Preferences["sidecarMode"] })}
              className="rounded-md border border-input bg-background px-2 py-1 text-sm"
            >
              <option value="snapshot">On</option>
              <option value="off">Off</option>
            </select>
          </div>
        </div>

        <div className="flex items-start justify-between gap-6 py-3 border-b border-border">
          <div className="space-y-0.5">
            <label htmlFor="sidecar-interval" className="text-sm font-medium">
              How often
            </label>
            <p className="text-xs text-muted-foreground">
              The server checks on its own schedule, so this can only make snapshots less
              frequent than that check, never more.
            </p>
          </div>
          <div className={`shrink-0 transition-opacity ${!enabled ? "opacity-50" : ""}`}>
            <select
              id="sidecar-interval"
              value={prefs.sidecarIntervalMinutes}
              disabled={!enabled}
              onChange={e => updatePreferences({
                sidecarIntervalMinutes: Number(e.target.value) as Preferences["sidecarIntervalMinutes"],
              })}
              className="rounded-md border border-input bg-background px-2 py-1 text-sm"
            >
              <option value={5}>Every 5 minutes</option>
              <option value={15}>Every 15 minutes</option>
              <option value={60}>Hourly</option>
              <option value={360}>Every 6 hours</option>
              <option value={1440}>Daily</option>
            </select>
          </div>
        </div>

        {serverDisabled && (
          <p className="text-xs text-destructive" role="status">
            Snapshots are turned off for this server (<code>SIDECAR_EXPORT_ENABLED=false</code>).
            Nothing is being backed up, and this setting cannot change that — it has to be
            changed in the server&apos;s environment.
          </p>
        )}

        <p className="text-xs text-muted-foreground" role="status">
          {status?.snapshot
            ? `Last snapshot ${formatWhen(status.snapshot.exportedAt)} — about ${status.snapshot.entries} items, ${formatBytes(status.snapshot.sizeBytes)}.`
            : "No snapshot written yet."}
        </p>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            size="sm"
            variant="outline"
            onClick={handleExport}
            disabled={!enabled || exporting || restoring}
            className="gap-1.5"
          >
            {exporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            Save snapshot now
          </Button>

          <Button
            size="sm"
            variant="outline"
            onClick={() => setConfirming(true)}
            disabled={!status?.snapshot || restoring}
            className="gap-1.5"
          >
            {restoring ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
            Restore from snapshot
          </Button>
        </div>

        {restoring && status?.restore?.state === "running" && (
          <p className="text-xs text-muted-foreground" role="status">
            Restoring — {status.restore.processed} item{status.restore.processed === 1 ? "" : "s"} read.
          </p>
        )}

        {status?.restore?.state === "interrupted" && (
          <p className="text-xs text-destructive" role="status">
            The last restore stopped partway, after {status.restore.processed} item
            {status.restore.processed === 1 ? "" : "s"} — the server most likely restarted while
            it was running. Nothing was left half-written: restoring again puts back whatever
            is still missing and leaves what already came back alone.
          </p>
        )}

        {confirming && (
          <div className="rounded-md border border-border bg-muted/40 p-3 space-y-2">
            <p className="text-xs">
              Restore reads the snapshot and puts back anything the library is missing:
              tags, titles you edited, starred state, bundles and reminders. It only fills
              gaps — existing titles, tags, stars and bundles are never overwritten, and no
              file or item is deleted. Tag counts are recomputed afterwards, which clears
              out tags that no longer have any items.
            </p>
            <div className="flex items-center gap-2">
              <Button size="sm" onClick={handleRestore}>Restore</Button>
              <Button size="sm" variant="ghost" onClick={() => setConfirming(false)}>Cancel</Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
